name: "Test Branch Name"
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
  
jobs:
  test_job:
    runs-on: ubuntu-latest
    name: A job to test branch name
    steps:
      - uses: knawat/github-actions-gitflow@v1